In [123]:
import numpy as np

# show full output
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"


# Numpy matrices and vectors

In [124]:
np.arange(start=1, stop = 5, step = 1)
# stop value not included

array([1, 2, 3, 4])

In [125]:
np.zeros(shape=(2,2))
# float by default

array([[0., 0.],
       [0., 0.]])

In [126]:
np.ones(shape=(2,2))

array([[1., 1.],
       [1., 1.]])

In [127]:
np.zeros(shape=(2,2))

array([[0., 0.],
       [0., 0.]])

In [128]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [129]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [130]:
np.linspace(start=1, stop=100, num = 10)
# evenly space sequence from start to stop with specified number fo values

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [131]:
np.full(shape=(2,2), fill_value=3)
np.full((2,2),3)

#np.full(shape=(2,2), 3) #is not working since it positional argument follows keyword argument

array([[3, 3],
       [3, 3]])

array([[3, 3],
       [3, 3]])

In [132]:
np.full(2,3)

array([3, 3])

In [133]:
np.empty(shape=(4,4))
# values close to zero

array([[4.67296746e-307, 1.69121096e-306, 1.86919378e-306,
        1.11256817e-306],
       [1.06811422e-306, 1.42417221e-306, 1.11260619e-306,
        8.90094053e-307],
       [1.86919378e-306, 1.06809792e-306, 1.37962456e-306,
        1.69111861e-306],
       [1.78020169e-306, 1.37961777e-306, 7.56599807e-307,
        7.56599806e-307]])

In [134]:
np.empty(2)

array([6.36598737e-314, 6.36598737e-314])

In [135]:
# random.rand(d0, d1, ..., dn)
np.random.rand(2,3)

array([[0.52503752, 0.00476548, 0.57022823],
       [0.00267938, 0.49858677, 0.42989815]])

In [136]:
#random.randint(low, high=None, size=None, dtype=int)
np.random.randint(low = 1, high = 49, size = 10)

array([32, 26,  7, 10, 39, 36,  8, 11, 25, 28])

# Data types and arrays

In [137]:
arr = np.array([1,2,3])

In [138]:
# retunr datatype
arr.dtype

dtype('int32')

In [139]:
arr = arr.astype('float')
arr.dtype

dtype('float64')

In [140]:
# Views

# created by .view()
a = arr.view()
a

# created by indexing
b = arr[:1]
b

# get base object of view
b.base


array([1., 2., 3.])

array([1.])

array([1., 2., 3.])

In [141]:
# Show if the array owns its own data or is just a view
b.flags.owndata
arr.flags.owndata

False

True

# Fancy indexing

In [147]:
mat = np.identity(4)
mat

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [150]:
# get vector of diagonal elemenst
# parwise combination of row and column
mat[[0,1,2,3],[0,1,2,3]]

array([1., 1., 1., 1.])

In [153]:
# over all columns get the second elemtent each
mat[0:3:2,0:3:2]

array([[1., 0.],
       [0., 1.]])

In [160]:
mat1 = np.ones(shape=(2,2))
mat2 = np.zeros(shape=(2,2))
mat1
mat2

# comparing matrices, relative tolerance, absolute tolerance
# np.allclose(a,b, rtol=1e-05, atol=1e-08, equal_nan=False)

np.allclose(mat1, mat2)

np.allclose(mat1,mat2, atol=1)

array([[1., 1.],
       [1., 1.]])

array([[0., 0.],
       [0., 0.]])

False

True

# Rehsaping arrays

In [165]:
# arange(stop):                 Values are generated within the half-open interval [0, stop)
# arange(start, stop):          Values are generated within the half-open interval [start, stop)
# arange(start, stop, step)     Values are generated within the half-open interval [start, stop), with spacing between values given by step

np.arange(10)
np.arange(0,10)
np.arange(0,10,1)

# 9 is excluded due to step size
np.arange(0,10,2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 2, 4, 6, 8])

In [201]:
arr = np.arange(1,10)
arr

# array method
# dont specify the shape argument
arr.reshape((3,3))

# Numopy function
arr = np.arange(1,10)
np.reshape(a = arr, newshape=(3,3))



array([1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [203]:
arr = np.arange(1,10)

# fills all other vlaues with 0
arr.resize((4,4))
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 0, 0],
       [0, 0, 0, 0]])

In [211]:
arr = np.arange(1,10)
arr

# append number to array
np.append(arr=arr, values=10, axis = None)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [230]:
#insert new value at second position
np.insert(arr=arr, obj = 1, values = 100, axis = None)

mat

# insert values in first row, axis = 0
np.insert(arr=mat, obj=0, values=[1,2,3,4], axis = 0)

# insert values in first column, axis = 1
np.insert(arr=mat, obj=0, values=[1,2,3,4], axis = 1)

array([  1, 100,   2,   3,   4,   5,   6,   7,   8,   9])

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

array([[1., 2., 3., 4.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

array([[1., 1., 0., 0., 0.],
       [2., 0., 1., 0., 0.],
       [3., 0., 0., 1., 0.],
       [4., 0., 0., 0., 1.]])

In [234]:
#delete first value in array
np.delete(arr=arr, obj=0)

# delete first row in matrix
np.delete(arr=mat, obj=0, axis=0)

# delete first column in matrix
np.delete(arr=mat, obj=0, axis=1)


array([2, 3, 4, 5, 6, 7, 8, 9])

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [246]:
# Shape and size
y = np.zeros((2, 2))
y

# get shape
y.shape
#get number of dimensions
y.ndim


array([[0., 0.],
       [0., 0.]])

(2, 2)

2

# Combining and splitting

In [272]:
#numpy.concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")

arr1 = np.arange(1,4)
arr1

arr2 = np.arange(4,7)
arr2

# concatenate rowwise
np.concatenate((arr1, arr2), axis = 0)
# stack horizontally
np.hstack((arr1,arr2))

# stack vertically
np.vstack((arr1,arr2))

# to concatenat ethe arrays as coluns, we have to make them to column vectors first
arr1 = arr1.reshape((3,1))
arr1
arr2 = arr2.reshape((3,1))
arr2

np.concatenate((arr1,arr2), axis = 1)

# concatenate columnwise
# np.vstack((arr1,arr2))

array([1, 2, 3])

array([4, 5, 6])

array([1, 2, 3, 4, 5, 6])

array([1, 2, 3, 4, 5, 6])

array([[1, 2, 3],
       [4, 5, 6]])

array([[1],
       [2],
       [3]])

array([[4],
       [5],
       [6]])

array([[1, 4],
       [2, 5],
       [3, 6]])

In [297]:
arr = np.arange(1,17).reshape(4,4)
arr

# split array into multiple sub-arrays as views int
# numpy.split(ary, indices_or_sections, axis=0)

# split rows into 3 arrays
np.split(ary=arr, indices_or_sections=4, axis = 0)

# split columns into 3 arrays
#np.split(ary=arr, indices_or_sections=4, axis = 1) 

# splits array at 3rd and 4th row
#np.split(ary=arr, indices_or_sections=[2,3], axis = 0)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]

# Summieren entlang der axe

Summieren entlang der axe bedeutet, die elemente entland der axis zu summieren


# Splitten entlang der axis

Splitten entlang der axis bedeutet, die elemente entlang der axis zu splitten

In [311]:
# understanding axes
arr = np.arange(1,10).reshape(3,3)
arr

# columwise sum
np.sum(arr, axis=0)

# rowwise sum
np.sum(arr, axis=1)

# split rows into 3 arrays
np.split(ary=arr, indices_or_sections=3, axis = 0)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([12, 15, 18])

array([ 6, 15, 24])

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [313]:
arr

# numpy.hsplit(ary, indices_or_sections)
# split columns of array into n sub arrays
#np.hsplit(ary=arr, indices_or_sections=4)
# same as 
np.split(ary=arr, indices_or_sections=3, axis=1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [322]:
# transposing a matrix or array

m = np.arange(1,10).reshape(3,3)
m
m.T

# Transposing only works with multidimensional arrays
arr = np.arange(1,10).reshape(1,9)
arr
arr.T

# example one dimensional
arr = np.arange(1,10)
arr
arr.T

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [332]:
# matrix multiplication
m = np.identity(3)
m

n = np.arange(1,10).reshape(3,3)
n

np.dot(m,n)
m @ n

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

array([[-1., -2., -3.],
       [-4., -5., -6.],
       [-7., -8., -9.]])

In [351]:
# other mathematical functions

arr = np.array([1,-2,3,-4,5,-6,7,-8,9]).reshape(3,3)
arr

#absolute value
np.abs(arr)

# square root
np.sqrt(arr)

# exponential
np.exp(arr)

# logs (log, log10, log2)
np.log(arr)
np.log10(arr)
np.log2(arr)

# get sign of values (return -1,0,1)
np.sign(arr)

# rounding up
np.ceil(arr)

#rounding down
np.floor(arr)

# round to nearest integer
np.rint(arr)

# return fractional parts
# this returns 2 arrays: one with the fractions and one with the integers
np.modf(arr)

# sin, cos and tan
np.sin(arr)

# round element-wise to nearest integer towards zero.
# The rounded values are returned as floats.
# this differs from np.floor for negative values and from np.ceil for positive values
np.fix(arr)

array([[ 1, -2,  3],
       [-4,  5, -6],
       [ 7, -8,  9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

C:\Users\Paul\AppData\Local\Temp\ipykernel_15508\2009262276.py:10: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([[1.        ,        nan, 1.73205081],
       [       nan, 2.23606798,        nan],
       [2.64575131,        nan, 3.        ]])

array([[2.71828183e+00, 1.35335283e-01, 2.00855369e+01],
       [1.83156389e-02, 1.48413159e+02, 2.47875218e-03],
       [1.09663316e+03, 3.35462628e-04, 8.10308393e+03]])

C:\Users\Paul\AppData\Local\Temp\ipykernel_15508\2009262276.py:16: RuntimeWarning: invalid value encountered in log
  np.log(arr)


array([[0.        ,        nan, 1.09861229],
       [       nan, 1.60943791,        nan],
       [1.94591015,        nan, 2.19722458]])

C:\Users\Paul\AppData\Local\Temp\ipykernel_15508\2009262276.py:17: RuntimeWarning: invalid value encountered in log10
  np.log10(arr)


array([[0.        ,        nan, 0.47712125],
       [       nan, 0.69897   ,        nan],
       [0.84509804,        nan, 0.95424251]])

C:\Users\Paul\AppData\Local\Temp\ipykernel_15508\2009262276.py:18: RuntimeWarning: invalid value encountered in log2
  np.log2(arr)


array([[0.        ,        nan, 1.5849625 ],
       [       nan, 2.32192809,        nan],
       [2.80735492,        nan, 3.169925  ]])

array([[ 1, -1,  1],
       [-1,  1, -1],
       [ 1, -1,  1]])

array([[ 1., -2.,  3.],
       [-4.,  5., -6.],
       [ 7., -8.,  9.]])

array([[ 1., -2.,  3.],
       [-4.,  5., -6.],
       [ 7., -8.,  9.]])

array([[ 1., -2.,  3.],
       [-4.,  5., -6.],
       [ 7., -8.,  9.]])

(array([[ 0., -0.,  0.],
        [-0.,  0., -0.],
        [ 0., -0.,  0.]]),
 array([[ 1., -2.,  3.],
        [-4.,  5., -6.],
        [ 7., -8.,  9.]]))

array([[ 0.84147098, -0.90929743,  0.14112001],
       [ 0.7568025 , -0.95892427,  0.2794155 ],
       [ 0.6569866 , -0.98935825,  0.41211849]])

array([[ 1., -2.,  3.],
       [-4.,  5., -6.],
       [ 7., -8.,  9.]])

# Binary functions

element-wise equations

In [364]:
a = np.array([1,2,3,4,5])
b = np.array([2,4,8,6,10])
a
b
print('NOW THE CALCULATIONS')
# element wise maximum
np.maximum(a,b)

np.greater_equal(a,b)

np.add(a,b)

np.mod(a,b) #modulo

np.subtract(a,b)

np.multiply(a,b)

np.divide(a,b)

np.greater(a,b)

np.less(a,b)

np.equal(a,b)

array([1, 2, 3, 4, 5])

array([ 2,  4,  8,  6, 10])

NOW THE CALCULATIONS


array([ 2,  4,  8,  6, 10])

array([False, False, False, False, False])

array([ 3,  6, 11, 10, 15])

array([1, 2, 3, 4, 5])

array([-1, -2, -5, -2, -5])

array([ 2,  8, 24, 24, 50])

array([0.5       , 0.5       , 0.375     , 0.66666667, 0.5       ])

array([False, False, False, False, False])

array([ True,  True,  True,  True,  True])

array([False, False, False, False, False])

# Meshgrid

In [367]:
# arange a meshgrid

p = np.arange(start=-5, stop=5, step=0.001)

x,y = np.meshgrid(p,p)
x
y

array([[-5.   , -4.999, -4.998, ...,  4.997,  4.998,  4.999],
       [-5.   , -4.999, -4.998, ...,  4.997,  4.998,  4.999],
       [-5.   , -4.999, -4.998, ...,  4.997,  4.998,  4.999],
       ...,
       [-5.   , -4.999, -4.998, ...,  4.997,  4.998,  4.999],
       [-5.   , -4.999, -4.998, ...,  4.997,  4.998,  4.999],
       [-5.   , -4.999, -4.998, ...,  4.997,  4.998,  4.999]])

array([[-5.   , -5.   , -5.   , ..., -5.   , -5.   , -5.   ],
       [-4.999, -4.999, -4.999, ..., -4.999, -4.999, -4.999],
       [-4.998, -4.998, -4.998, ..., -4.998, -4.998, -4.998],
       ...,
       [ 4.997,  4.997,  4.997, ...,  4.997,  4.997,  4.997],
       [ 4.998,  4.998,  4.998, ...,  4.998,  4.998,  4.998],
       [ 4.999,  4.999,  4.999, ...,  4.999,  4.999,  4.999]])

# conditional logic

In [370]:
a

np.where(a <= 3, a, 0)

array([1, 2, 3, 4, 5])

array([1, 2, 3, 0, 0])

# Statistical methods

In [377]:
a


# these methods are only applicable for numpy arrays and DONT WORK FOR LISTS!!!!
a.sum()
a.mean()
a.std()
a.var()
a.min()
a.max()

# get the array index of the minimum/maximum
a.argmin()
a.argmax()

array([1, 2, 3, 4, 5])

15

3.0

1.4142135623730951

2.0

1

5

0

4

# Sorting

In [395]:
#numpy.sort(a, axis=-1, kind=None, order=None)

# axis = -1 sorts along the last axis: for 2 dimensions it sorts axis = 1
# kind = {'quicksort', 'mergesort', 'heatspot', 'stable'} optional


# random.randint(low, high=None, size=None, dtype=int)
# random.rand(d0, d1, ..., dn) d are the dimesnion of the output array


a = np.random.randint(low = 1, high=10, size=10)
a
a.sort()
a

array([4, 7, 4, 1, 6, 5, 7, 7, 1, 8])

array([1, 1, 4, 4, 5, 6, 7, 7, 7, 8])

# Linear algebra

In [398]:
# functions implemented in default numpy

m = np.arange(1,10).reshape(3,3)
m

# trace of a matrix (su of diagonal elements)
np.trace(m)

# diagonal elements
np.diag(m)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

15

array([1, 5, 9])

In [434]:
import numpy.linalg as nplin

# set seed
np.random.seed(seed=2)

# low inclusive, high exclusive
m = np.array([3,0,0,0,1,0,0,0,2]).reshape(3,3)
m

# inverse of a matrix
nplin.inv(m)

# determinant of a matrix
nplin.det(m)

# compute eigenvalues and eigenvector
eigenval, eigenvec = nplin.eig(m)
eigenval
eigenvec

# check computation: vec*val gives matrix
(eigenvec*eigenval == m).all()

# dot product retonr
np.dot(m, eigenvec)

array([[3, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

array([[0.33333333, 0.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 0.        , 0.5       ]])

6.0

array([3., 1., 2.])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

True

array([[3., 0., 0.],
       [0., 1., 0.],
       [0., 0., 2.]])

# QR decomposition

In [438]:
Q, R = nplin.qr(m)
Q
R

# m = Q * R
(m == np.dot(Q,R)).all()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[3., 0., 0.],
       [0., 1., 0.],
       [0., 0., 2.]])

True

# Solve linear system

Ax = b

In [448]:
M = m
M

b = np.ones(3)
b

a = nplin.solve(m,b)
a

# check coorect comutation
np.allclose(np.dot(m,b),a, atol = 1)

array([[3, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

array([1., 1., 1.])

array([0.33333333, 1.        , 0.5       ])

False