# Matrix transposition

In [5]:
import numpy as np

# show full output
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# k is equal to n transposed

n = np.arange(9).reshape((3, 3))
n

k = np.array([[0, 3, 6], [1, 4, 7], [2, 5, 8]])
k

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [14]:
# correct and efficient way

n = np.arange(9).reshape((3, 3))
n
for i in range(0, 3):
    for j in range(0, i): #tis is necessary to see that the  
        if i != j:
            p = n[i, j]
            n[i, j] = n[j, i]
            n[j, i] = p

print(n)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

[[0 3 6]
 [1 4 7]
 [2 5 8]]


# Matrix multiplication

In [24]:
# Matrix multiplication

A = np.array([[4, 3, 6], [1, 4, 7], [2, 5, 8]])

B = np.zeros([3,3])
for i in range(3):
    for k in range(3):
        for j in range(3):
            B[i][k] = B[i][k] + A[i][j] * A[j][k]
print(B)

np.allclose(np.dot(A,A),B)



[[ 31.  54.  93.]
 [ 22.  54.  90.]
 [ 29.  66. 111.]]


True